// <auto-generated />
using System;
using Intranet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intranet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260823195716_ActualizarUsuarioYVacaciones")]
    partial class ActualizarUsuarioYVacaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intranet.Models.Area", b =>
                {
                    b.Property<long>("IdArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdArea"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdArea");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            IdArea = 1L,
                            Estado = true,
                            Nombre = "Gerencial"
                        },
                        new
                        {
                            IdArea = 2L,
                            Estado = true,
                            Nombre = "Tecnología"
                        },
                        new
                        {
                            IdArea = 3L,
                            Estado = true,
                            Nombre = "Crédito"
                        },
                        new
                        {
                            IdArea = 4L,
                            Estado = true,
                            Nombre = "Financiero"
                        },
                        new
                        {
                            IdArea = 5L,
                            Estado = true,
                            Nombre = "Comercial"
                        },
                        new
                        {
                            IdArea = 6L,
                            Estado = true,
                            Nombre = "Talento Humano"
                        },
                        new
                        {
                            IdArea = 7L,
                            Estado = true,
                            Nombre = "Marketing"
                        },
                        new
                        {
                            IdArea = 8L,
                            Estado = true,
                            Nombre = "Administrativo"
                        });
                });

            modelBuilder.Entity("Intranet.Models.Banco", b =>
                {
                    b.Property<long>("IdBanco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdBanco"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdBanco");

                    b.ToTable("Bancos");

                    b.HasData(
                        new
                        {
                            IdBanco = 1L,
                            Estado = true,
                            Nombre = "Banco Pichincha"
                        },
                        new
                        {
                            IdBanco = 2L,
                            Estado = true,
                            Nombre = "Banco Guayaquil"
                        },
                        new
                        {
                            IdBanco = 3L,
                            Estado = true,
                            Nombre = "Banco del Pacífico"
                        },
                        new
                        {
                            IdBanco = 4L,
                            Estado = true,
                            Nombre = "Produbanco"
                        },
                        new
                        {
                            IdBanco = 5L,
                            Estado = true,
                            Nombre = "Banco Internacional"
                        },
                        new
                        {
                            IdBanco = 6L,
                            Estado = true,
                            Nombre = "Banco del Austro"
                        },
                        new
                        {
                            IdBanco = 7L,
                            Estado = true,
                            Nombre = "Banco Bolivariano"
                        },
                        new
                        {
                            IdBanco = 8L,
                            Estado = true,
                            Nombre = "Banco Solidario"
                        },
                        new
                        {
                            IdBanco = 9L,
                            Estado = true,
                            Nombre = "Banco General Rumiñahui"
                        },
                        new
                        {
                            IdBanco = 10L,
                            Estado = true,
                            Nombre = "Banco de Machala"
                        },
                        new
                        {
                            IdBanco = 11L,
                            Estado = true,
                            Nombre = "Banco de Loja"
                        },
                        new
                        {
                            IdBanco = 12L,
                            Estado = true,
                            Nombre = "Banco Diners Club"
                        },
                        new
                        {
                            IdBanco = 13L,
                            Estado = true,
                            Nombre = "Cooperativa JEP"
                        },
                        new
                        {
                            IdBanco = 14L,
                            Estado = true,
                            Nombre = "Cooperativa Policía Nacional"
                        },
                        new
                        {
                            IdBanco = 15L,
                            Estado = true,
                            Nombre = "Cooperativa Alianza del Valle"
                        },
                        new
                        {
                            IdBanco = 16L,
                            Estado = true,
                            Nombre = "Cooperativa Andalucía"
                        },
                        new
                        {
                            IdBanco = 17L,
                            Estado = true,
                            Nombre = "Cooperativa San Francisco"
                        },
                        new
                        {
                            IdBanco = 18L,
                            Estado = true,
                            Nombre = "Mutualista Pichincha"
                        });
                });

            modelBuilder.Entity("Intranet.Models.Cargo", b =>
                {
                    b.Property<long>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCargo"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<long>("IdArea")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCargo");

                    b.HasIndex("IdArea");

                    b.ToTable("Cargos");

                    b.HasData(
                        new
                        {
                            IdCargo = 1L,
                            Estado = true,
                            IdArea = 1L,
                            Nombre = "Gerente General"
                        },
                        new
                        {
                            IdCargo = 2L,
                            Estado = true,
                            IdArea = 2L,
                            Nombre = "Analista de Procesos"
                        },
                        new
                        {
                            IdCargo = 3L,
                            Estado = true,
                            IdArea = 3L,
                            Nombre = "Jefe de Crédito"
                        },
                        new
                        {
                            IdCargo = 4L,
                            Estado = true,
                            IdArea = 2L,
                            Nombre = "Gerente de Operaciones"
                        },
                        new
                        {
                            IdCargo = 5L,
                            Estado = true,
                            IdArea = 2L,
                            Nombre = "Ingeniero en Infraestructura"
                        },
                        new
                        {
                            IdCargo = 6L,
                            Estado = true,
                            IdArea = 4L,
                            Nombre = "Asistente Contable"
                        },
                        new
                        {
                            IdCargo = 7L,
                            Estado = true,
                            IdArea = 5L,
                            Nombre = "Ejecutivo de Cuentas"
                        },
                        new
                        {
                            IdCargo = 8L,
                            Estado = true,
                            IdArea = 5L,
                            Nombre = "Promotor"
                        },
                        new
                        {
                            IdCargo = 9L,
                            Estado = true,
                            IdArea = 2L,
                            Nombre = "Asistente de Infraestructura"
                        },
                        new
                        {
                            IdCargo = 10L,
                            Estado = true,
                            IdArea = 6L,
                            Nombre = "Jefe de Recursos Humanos"
                        },
                        new
                        {
                            IdCargo = 11L,
                            Estado = true,
                            IdArea = 5L,
                            Nombre = "Coordinador de Negocios"
                        },
                        new
                        {
                            IdCargo = 12L,
                            Estado = true,
                            IdArea = 3L,
                            Nombre = "Analista de Datos"
                        },
                        new
                        {
                            IdCargo = 13L,
                            Estado = true,
                            IdArea = 3L,
                            Nombre = "Monitor de Cobranza"
                        },
                        new
                        {
                            IdCargo = 14L,
                            Estado = true,
                            IdArea = 7L,
                            Nombre = "Community Manager"
                        },
                        new
                        {
                            IdCargo = 15L,
                            Estado = true,
                            IdArea = 3L,
                            Nombre = "Asistente de Crédito"
                        },
                        new
                        {
                            IdCargo = 16L,
                            Estado = true,
                            IdArea = 8L,
                            Nombre = "Auxiliar de Servicios"
                        },
                        new
                        {
                            IdCargo = 17L,
                            Estado = true,
                            IdArea = 3L,
                            Nombre = "Servicio al Cliente"
                        },
                        new
                        {
                            IdCargo = 18L,
                            Estado = true,
                            IdArea = 4L,
                            Nombre = "Contador General"
                        },
                        new
                        {
                            IdCargo = 19L,
                            Estado = true,
                            IdArea = 5L,
                            Nombre = "Jefe de Negocios"
                        },
                        new
                        {
                            IdCargo = 20L,
                            Estado = true,
                            IdArea = 2L,
                            Nombre = "Pasante de Sistemas"
                        },
                        new
                        {
                            IdCargo = 21L,
                            Estado = true,
                            IdArea = 6L,
                            Nombre = "Pasante de Talento Humano"
                        },
                        new
                        {
                            IdCargo = 22L,
                            Estado = true,
                            IdArea = 7L,
                            Nombre = "Pasante de Diseño"
                        },
                        new
                        {
                            IdCargo = 23L,
                            Estado = true,
                            IdArea = 4L,
                            Nombre = "Analista Contable"
                        });
                });

            modelBuilder.Entity("Intranet.Models.Ciudad", b =>
                {
                    b.Property<long>("IdCiudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCiudad"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<long>("IdProvincia")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ProvinciaIdProvincia")
                        .HasColumnType("bigint");

                    b.HasKey("IdCiudad");

                    b.HasIndex("ProvinciaIdProvincia");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("Intranet.Models.ContactoEmergencia", b =>
                {
                    b.Property<long>("IdContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdContacto"));

                    b.Property<string>("Apellido")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Parentesco")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<long>("UsuarioIdUsuario")
                        .HasColumnType("bigint");

                    b.HasKey("IdContacto");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("ContactoEmergencia");
                });

            modelBuilder.Entity("Intranet.Models.DatoBancario", b =>
                {
                    b.Property<long>("IdDatoBancario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdDatoBancario"));

                    b.Property<long>("BancoIdBanco")
                        .HasColumnType("bigint");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<long>("IdBanco")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UsuarioIdUsuario")
                        .HasColumnType("bigint");

                    b.HasKey("IdDatoBancario");

                    b.HasIndex("BancoIdBanco");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("DatoBancario");
                });

            modelBuilder.Entity("Intranet.Models.EstadoCivil", b =>
                {
                    b.Property<long>("IdEstadoCivil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdEstadoCivil"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEstadoCivil");

                    b.ToTable("EstadosCiviles");
                });

            modelBuilder.Entity("Intranet.Models.Etnia", b =>
                {
                    b.Property<long>("IdEtnia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdEtnia"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEtnia");

                    b.ToTable("Etnias");
                });

            modelBuilder.Entity("Intranet.Models.Familiar", b =>
                {
                    b.Property<long>("IdFamiliar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdFamiliar"));

                    b.Property<string>("Apellido")
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Parentesco")
                        .HasColumnType("text");

                    b.Property<long>("UsuarioIdUsuario")
                        .HasColumnType("bigint");

                    b.HasKey("IdFamiliar");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Familiar");
                });

            modelBuilder.Entity("Intranet.Models.Genero", b =>
                {
                    b.Property<long>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdGenero"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdGenero");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("Intranet.Models.Provincia", b =>
                {
                    b.Property<long>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdProvincia"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<long>("IdRegion")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RegionIdRegion")
                        .HasColumnType("bigint");

                    b.HasKey("IdProvincia");

                    b.HasIndex("RegionIdRegion");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("Intranet.Models.Region", b =>
                {
                    b.Property<long>("IdRegion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdRegion"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRegion");

                    b.ToTable("Regiones");
                });

            modelBuilder.Entity("Intranet.Models.Rol", b =>
                {
                    b.Property<long>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Intranet.Models.Titulo", b =>
                {
                    b.Property<long>("IdTitulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdTitulo"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaObtencion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<string>("Institucion")
                        .HasColumnType("text");

                    b.Property<string>("NombreTitulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UsuarioIdUsuario")
                        .HasColumnType("bigint");

                    b.HasKey("IdTitulo");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Titulo");
                });

            modelBuilder.Entity("Intranet.Models.Usuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("CargoIdCargo")
                        .HasColumnType("bigint");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("CiudadIdCiudad")
                        .HasColumnType("bigint");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorreoEmpresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorreoPersonal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DebeCambiarContrasena")
                        .HasColumnType("boolean");

                    b.Property<int>("DiasVacacionesAsignados")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<long?>("EstadoCivilIdEstadoCivil")
                        .HasColumnType("bigint");

                    b.Property<long?>("EtniaIdEtnia")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("GeneroIdGenero")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdCargo")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdCiudad")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdEstadoCivil")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdEtnia")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdGenero")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdRol")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("RolIdRol")
                        .HasColumnType("bigint");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("UrlImagenPerfil")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.HasIndex("CargoIdCargo");

                    b.HasIndex("CiudadIdCiudad");

                    b.HasIndex("EstadoCivilIdEstadoCivil");

                    b.HasIndex("EtniaIdEtnia");

                    b.HasIndex("GeneroIdGenero");

                    b.HasIndex("RolIdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Intranet.Models.Vacacion", b =>
                {
                    b.Property<long>("IdVacacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdVacacion"));

                    b.Property<int>("DiasTomados")
                        .HasColumnType("integer");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdRegistradoPor")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdVacacion");

                    b.HasIndex("IdRegistradoPor");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Vacaciones");
                });

            modelBuilder.Entity("Intranet.Models.Cargo", b =>
                {
                    b.HasOne("Intranet.Models.Area", "Area")
                        .WithMany("Cargos")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Intranet.Models.Ciudad", b =>
                {
                    b.HasOne("Intranet.Models.Provincia", "Provincia")
                        .WithMany("Ciudades")
                        .HasForeignKey("ProvinciaIdProvincia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Intranet.Models.ContactoEmergencia", b =>
                {
                    b.HasOne("Intranet.Models.Usuario", "Usuario")
                        .WithMany("ContactosEmergencia")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Intranet.Models.DatoBancario", b =>
                {
                    b.HasOne("Intranet.Models.Banco", "Banco")
                        .WithMany("DatosBancarios")
                        .HasForeignKey("BancoIdBanco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intranet.Models.Usuario", "Usuario")
                        .WithMany("DatosBancarios")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Intranet.Models.Familiar", b =>
                {
                    b.HasOne("Intranet.Models.Usuario", "Usuario")
                        .WithMany("Familiares")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Intranet.Models.Provincia", b =>
                {
                    b.HasOne("Intranet.Models.Region", "Region")
                        .WithMany("Provincias")
                        .HasForeignKey("RegionIdRegion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Intranet.Models.Titulo", b =>
                {
                    b.HasOne("Intranet.Models.Usuario", "Usuario")
                        .WithMany("Titulos")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Intranet.Models.Usuario", b =>
                {
                    b.HasOne("Intranet.Models.Cargo", "Cargo")
                        .WithMany("Usuarios")
                        .HasForeignKey("CargoIdCargo");

                    b.HasOne("Intranet.Models.Ciudad", "Ciudad")
                        .WithMany("Usuarios")
                        .HasForeignKey("CiudadIdCiudad");

                    b.HasOne("Intranet.Models.EstadoCivil", "EstadoCivil")
                        .WithMany("Usuarios")
                        .HasForeignKey("EstadoCivilIdEstadoCivil");

                    b.HasOne("Intranet.Models.Etnia", "Etnia")
                        .WithMany("Usuarios")
                        .HasForeignKey("EtniaIdEtnia");

                    b.HasOne("Intranet.Models.Genero", "Genero")
                        .WithMany("Usuarios")
                        .HasForeignKey("GeneroIdGenero");

                    b.HasOne("Intranet.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolIdRol");

                    b.Navigation("Cargo");

                    b.Navigation("Ciudad");

                    b.Navigation("EstadoCivil");

                    b.Navigation("Etnia");

                    b.Navigation("Genero");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Intranet.Models.Vacacion", b =>
                {
                    b.HasOne("Intranet.Models.Usuario", "RegistradoPor")
                        .WithMany("VacacionesRegistradas")
                        .HasForeignKey("IdRegistradoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Intranet.Models.Usuario", "Usuario")
                        .WithMany("VacacionesRecibidas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegistradoPor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Intranet.Models.Area", b =>
                {
                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("Intranet.Models.Banco", b =>
                {
                    b.Navigation("DatosBancarios");
                });

            modelBuilder.Entity("Intranet.Models.Cargo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Intranet.Models.Ciudad", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Intranet.Models.EstadoCivil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Intranet.Models.Etnia", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Intranet.Models.Genero", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Intranet.Models.Provincia", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("Intranet.Models.Region", b =>
                {
                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("Intranet.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Intranet.Models.Usuario", b =>
                {
                    b.Navigation("ContactosEmergencia");

                    b.Navigation("DatosBancarios");

                    b.Navigation("Familiares");

                    b.Navigation("Titulos");

                    b.Navigation("VacacionesRecibidas");

                    b.Navigation("VacacionesRegistradas");
                });
#pragma warning restore 612, 618
        }
    }
}
