// <auto-generated />
using System;
using Intranet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intranet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817031030_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intranet.Models.Area", b =>
                {
                    b.Property<long>("IdArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_area");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdArea"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdArea");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.Banco", b =>
                {
                    b.Property<long>("IdBanco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_banco");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdBanco"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("IdBanco");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("bancos", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.Cargo", b =>
                {
                    b.Property<long>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_cargo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCargo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<long>("IdArea")
                        .HasColumnType("bigint")
                        .HasColumnName("id_area");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCargo");

                    b.HasIndex("IdArea", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("uq_cargo_area");

                    b.ToTable("cargos", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.Ciudad", b =>
                {
                    b.Property<long>("IdCiudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_ciudad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCiudad"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<long>("IdProvincia")
                        .HasColumnType("bigint")
                        .HasColumnName("id_provincia");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCiudad");

                    b.HasIndex("IdProvincia", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("uq_ciudad_provincia");

                    b.ToTable("ciudades", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.ContactoEmergencia", b =>
                {
                    b.Property<long>("IdContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_contacto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdContacto"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("direccion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Parentesco")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parentesco");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.HasKey("IdContacto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("contactos_emergencia", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.DatoBancario", b =>
                {
                    b.Property<long>("IdDatoBancario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_dato_bancario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdDatoBancario"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<long>("IdBanco")
                        .HasColumnType("bigint")
                        .HasColumnName("id_banco");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_cuenta");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_cuenta");

                    b.HasKey("IdDatoBancario");

                    b.HasIndex("IdBanco");

                    b.HasIndex("IdUsuario");

                    b.ToTable("datos_bancarios", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.EstadoCivil", b =>
                {
                    b.Property<long>("IdEstadoCivil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_estado_civil");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdEstadoCivil"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstadoCivil");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("estados_civiles", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.Etnia", b =>
                {
                    b.Property<long>("IdEtnia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_etnia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdEtnia"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEtnia");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("etnias", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.Familiar", b =>
                {
                    b.Property<long>("IdFamiliar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_familiar");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdFamiliar"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Parentesco")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parentesco");

                    b.HasKey("IdFamiliar");

                    b.HasIndex("IdUsuario");

                    b.ToTable("familiares", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.Genero", b =>
                {
                    b.Property<long>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_genero");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdGenero"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdGenero");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("generos", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.Imagen", b =>
                {
                    b.Property<long>("IdImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_imagen");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdImagen"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<string>("RutaImagen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ruta_imagen");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.HasKey("IdImagen");

                    b.ToTable("imagenes", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.Provincia", b =>
                {
                    b.Property<long>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_provincia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdProvincia"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<long>("IdRegion")
                        .HasColumnType("bigint")
                        .HasColumnName("id_region");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdProvincia");

                    b.HasIndex("IdRegion", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("uq_provincia_region");

                    b.ToTable("provincias", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.Region", b =>
                {
                    b.Property<long>("IdRegion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_region");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdRegion"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRegion");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("regiones", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.Rol", b =>
                {
                    b.Property<long>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.Titulo", b =>
                {
                    b.Property<long>("IdTitulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_titulo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdTitulo"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaObtencion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_obtencion");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Institucion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("institucion");

                    b.Property<string>("NombreTitulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_titulo");

                    b.HasKey("IdTitulo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("titulos", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.Usuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cedula");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("CorreoEmpresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo_empresa");

                    b.Property<bool>("DebeCambiarContrasena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("debe_cambiar_contrasena");

                    b.Property<int>("DiasVacacionesAsignados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15)
                        .HasColumnName("dias_vacaciones_asignados");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("direccion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<long?>("IdCargo")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cargo");

                    b.Property<long?>("IdCiudad")
                        .HasColumnType("bigint")
                        .HasColumnName("id_ciudad");

                    b.Property<long?>("IdEstadoCivil")
                        .HasColumnType("bigint")
                        .HasColumnName("id_estado_civil");

                    b.Property<long?>("IdEtnia")
                        .HasColumnType("bigint")
                        .HasColumnName("id_etnia");

                    b.Property<long?>("IdGenero")
                        .HasColumnType("bigint")
                        .HasColumnName("id_genero");

                    b.Property<long>("IdRol")
                        .HasColumnType("bigint")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("UrlImagenPerfil")
                        .HasColumnType("text")
                        .HasColumnName("url_imagen_perfil");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("CorreoEmpresa")
                        .IsUnique();

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdCiudad");

                    b.HasIndex("IdEstadoCivil");

                    b.HasIndex("IdEtnia");

                    b.HasIndex("IdGenero");

                    b.HasIndex("IdRol");

                    b.HasIndex("UsuarioNombre")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.Vacacion", b =>
                {
                    b.Property<long>("IdVacacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_vacacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdVacacion"));

                    b.Property<int>("DiasTomados")
                        .HasColumnType("integer")
                        .HasColumnName("dias_tomados");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("IdRegistradoPor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_registrado_por");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacion");

                    b.HasKey("IdVacacion");

                    b.HasIndex("IdRegistradoPor");

                    b.HasIndex("IdUsuario");

                    b.ToTable("vacaciones", (string)null);
                });

            modelBuilder.Entity("Intranet.Models.Cargo", b =>
                {
                    b.HasOne("Intranet.Models.Area", "Area")
                        .WithMany("Cargos")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cargo_area");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Intranet.Models.Ciudad", b =>
                {
                    b.HasOne("Intranet.Models.Provincia", "Provincia")
                        .WithMany("Ciudades")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ciudad_provincia");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Intranet.Models.ContactoEmergencia", b =>
                {
                    b.HasOne("Intranet.Models.Usuario", "Usuario")
                        .WithMany("ContactosEmergencia")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Intranet.Models.DatoBancario", b =>
                {
                    b.HasOne("Intranet.Models.Banco", "Banco")
                        .WithMany("DatosBancarios")
                        .HasForeignKey("IdBanco")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Intranet.Models.Usuario", "Usuario")
                        .WithMany("DatosBancarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Intranet.Models.Familiar", b =>
                {
                    b.HasOne("Intranet.Models.Usuario", "Usuario")
                        .WithMany("Familiares")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Intranet.Models.Provincia", b =>
                {
                    b.HasOne("Intranet.Models.Region", "Region")
                        .WithMany("Provincias")
                        .HasForeignKey("IdRegion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_provincia_region");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Intranet.Models.Titulo", b =>
                {
                    b.HasOne("Intranet.Models.Usuario", "Usuario")
                        .WithMany("Titulos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Intranet.Models.Usuario", b =>
                {
                    b.HasOne("Intranet.Models.Cargo", "Cargo")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Intranet.Models.Ciudad", "Ciudad")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdCiudad")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Intranet.Models.EstadoCivil", "EstadoCivil")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEstadoCivil")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Intranet.Models.Etnia", "Etnia")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEtnia")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Intranet.Models.Genero", "Genero")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdGenero")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Intranet.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Ciudad");

                    b.Navigation("EstadoCivil");

                    b.Navigation("Etnia");

                    b.Navigation("Genero");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Intranet.Models.Vacacion", b =>
                {
                    b.HasOne("Intranet.Models.Usuario", "RegistradoPor")
                        .WithMany("VacacionesRegistradas")
                        .HasForeignKey("IdRegistradoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Intranet.Models.Usuario", "Usuario")
                        .WithMany("VacacionesRecibidas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistradoPor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Intranet.Models.Area", b =>
                {
                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("Intranet.Models.Banco", b =>
                {
                    b.Navigation("DatosBancarios");
                });

            modelBuilder.Entity("Intranet.Models.Cargo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Intranet.Models.Ciudad", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Intranet.Models.EstadoCivil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Intranet.Models.Etnia", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Intranet.Models.Genero", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Intranet.Models.Provincia", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("Intranet.Models.Region", b =>
                {
                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("Intranet.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Intranet.Models.Usuario", b =>
                {
                    b.Navigation("ContactosEmergencia");

                    b.Navigation("DatosBancarios");

                    b.Navigation("Familiares");

                    b.Navigation("Titulos");

                    b.Navigation("VacacionesRecibidas");

                    b.Navigation("VacacionesRegistradas");
                });
#pragma warning restore 612, 618
        }
    }
}
